"""Route manifest for auth service API discovery."""

from shared.core.registry import RouteDefinition, SecurityGroup, ServiceManifest

from .routes import (
    activate_user,
    assign_role,
    change_password,
    deactivate_user,
    delete_user,
    get_my_profile,
    get_user,
    list_users,
    login,
    logout,
    refresh_token,
    register,
    request_password_reset,
    reset_password,
    update_my_profile,
    update_user,
    verify_email,
)

# Create service manifest with all routes
manifest = ServiceManifest(
    service_name="auth",
    version="1.0.0",
    description="Authentication and user management service",
    routes=[
        # Public routes
        RouteDefinition(
            path="/register",
            method="POST",
            handler=register,
            security_group=SecurityGroup.PUBLIC,
            description="Register new user",
            tags=["auth"],
        ),
        RouteDefinition(
            path="/login",
            method="POST",
            handler=login,
            security_group=SecurityGroup.PUBLIC,
            description="Login user",
            tags=["auth"],
        ),
        RouteDefinition(
            path="/refresh",
            method="POST",
            handler=refresh_token,
            security_group=SecurityGroup.PUBLIC,
            description="Refresh access token",
            tags=["auth"],
        ),
        RouteDefinition(
            path="/password-reset",
            method="POST",
            handler=request_password_reset,
            security_group=SecurityGroup.PUBLIC,
            description="Request password reset",
            tags=["auth"],
        ),
        RouteDefinition(
            path="/password-reset/confirm",
            method="POST",
            handler=reset_password,
            security_group=SecurityGroup.PUBLIC,
            description="Reset password with token",
            tags=["auth"],
        ),
        RouteDefinition(
            path="/verify-email",
            method="POST",
            handler=verify_email,
            security_group=SecurityGroup.PUBLIC,
            description="Verify email address",
            tags=["auth"],
        ),
        # Authenticated routes
        RouteDefinition(
            path="/users/me",
            method="GET",
            handler=get_my_profile,
            security_group=SecurityGroup.AUTHENTICATED,
            description="Get current user profile",
            tags=["users"],
        ),
        RouteDefinition(
            path="/users/me",
            method="PATCH",
            handler=update_my_profile,
            security_group=SecurityGroup.AUTHENTICATED,
            description="Update current user profile",
            tags=["users"],
        ),
        RouteDefinition(
            path="/logout",
            method="POST",
            handler=logout,
            security_group=SecurityGroup.AUTHENTICATED,
            description="Logout current user",
            tags=["auth"],
        ),
        RouteDefinition(
            path="/change-password",
            method="POST",
            handler=change_password,
            security_group=SecurityGroup.AUTHENTICATED,
            description="Change password",
            tags=["auth"],
        ),
        # Admin routes
        RouteDefinition(
            path="/users",
            method="GET",
            handler=list_users,
            security_group=SecurityGroup.ADMIN,
            description="List all users",
            tags=["admin", "users"],
        ),
        RouteDefinition(
            path="/users/{user_id}",
            method="GET",
            handler=get_user,
            security_group=SecurityGroup.ADMIN,
            description="Get user details",
            tags=["admin", "users"],
        ),
        RouteDefinition(
            path="/users/{user_id}",
            method="PATCH",
            handler=update_user,
            security_group=SecurityGroup.ADMIN,
            description="Update user",
            tags=["admin", "users"],
        ),
        RouteDefinition(
            path="/users/{user_id}",
            method="DELETE",
            handler=delete_user,
            security_group=SecurityGroup.ADMIN,
            description="Delete user",
            tags=["admin", "users"],
        ),
        RouteDefinition(
            path="/users/{user_id}/activate",
            method="POST",
            handler=activate_user,
            security_group=SecurityGroup.ADMIN,
            description="Activate user account",
            tags=["admin", "users"],
        ),
        RouteDefinition(
            path="/users/{user_id}/deactivate",
            method="POST",
            handler=deactivate_user,
            security_group=SecurityGroup.ADMIN,
            description="Deactivate user account",
            tags=["admin", "users"],
        ),
        RouteDefinition(
            path="/users/{user_id}/assign-role",
            method="POST",
            handler=assign_role,
            security_group=SecurityGroup.ADMIN,
            description="Assign role to user",
            tags=["admin", "users"],
        ),
    ],
    health_check_path="/health",
)