version: "3.9"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,sqs
      - DEBUG=0
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN-}
      - AWS_DEFAULT_REGION=${AWS_REGION:-eu-west-2}
    ports:
      - "4566:4566" # edge port
    volumes:
      - localstack-data:/var/lib/localstack

volumes:
  localstack-data: {}
