"""Ports for event consumption and persistence."""

from typing import Protocol


class JobRepository(Protocol):
    def mark_running(self, correlation_id: str) -> None: ...
    def mark_completed(self, correlation_id: str, result: dict) -> None: ...
    def mark_failed(self, correlation_id: str, error: str) -> None: ...
    def is_canceled(self, correlation_id: str) -> bool: ...
