python_sources(
    sources=["*.py"],
    resolve="test",
)

python_tests(
    name="test_setup",
    sources=["test_setup_tools.py"],
    tags=["unit", "setup"],
    resolve="test",
)

python_tests(
    name="test_verify",
    sources=["test_verify_tools.py"],
    tags=["unit", "setup"],
    resolve="test",
)