python_sources(
    sources=["**/*.py"],
    resolve="test",  # Use test resolve
    dependencies=[
        "//3rdparty/python:shared_reqs#pydantic",
        "//3rdparty/python:shared_reqs#pydantic-settings",
        "//3rdparty/python:shared_reqs#passlib",
        "//3rdparty/python:shared_reqs#python-jose",
        "//3rdparty/python:shared_reqs#boto3",
        "//3rdparty/python:shared_reqs#redis",
    ],
)
