from typing import Protocol


class QueuePort(Protocol):
    def publish(self, job_type: str, params: dict) -> str:  # returns correlation id
        ...


class JobRepository(Protocol):
    def get_status(self, correlation_id: str) -> dict | None: ...

    def mark_running(self, correlation_id: str) -> None: ...

    def mark_completed(self, correlation_id: str, result: dict) -> None: ...

    def mark_failed(self, correlation_id: str, error: str) -> None: ...

    def mark_canceled(self, correlation_id: str) -> None: ...
