name: block-direct-main
on:
  push:
    branches: [main]
jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - name: Fail on direct push to main
        run: |
          echo "Direct pushes to main are not allowed. Use PR from dev." >&2
          exit 1

