name: block-direct-main
on:
  push:
    branches: [main]
jobs:
  check-push-type:
    runs-on: ubuntu-latest
    steps:
      - name: Check if push is from PR merge
        run: |
          # Check if this is a merge commit from a PR
          # PR merges have specific patterns in commit messages

          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          PUSHER="${{ github.event.pusher.name }}"

          # GitHub PR merges typically have these patterns:
          # - Start with "Merge pull request #"
          # - Or contain "(#" followed by PR number
          # - Or start with specific PR merge patterns

          if [[ "$COMMIT_MESSAGE" =~ ^Merge\ pull\ request\ \# ]] || \
             [[ "$COMMIT_MESSAGE" =~ \(\#[0-9]+\)$ ]] || \
             [[ "$COMMIT_MESSAGE" =~ ^[a-zA-Z]+:.*\(\#[0-9]+\) ]]; then
            echo "✅ This is a PR merge to main - allowed"
            echo "Merged by: $PUSHER"
            echo "Commit: $COMMIT_MESSAGE"
            exit 0
          else
            echo "❌ Direct pushes to main are not allowed. Use PR from dev." >&2
            echo "Attempted by: $PUSHER"
            echo "Commit: $COMMIT_MESSAGE"
            exit 1
          fi
