name: ci
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pants
            ./.pants.d
          key: pants-${{ runner.os }}-${{ hashFiles('**/*.BUILD','pants.toml','lockfiles/*.lock','**/requirements*.txt') }}
      - uses: pantsbuild/actions/setup-pants@v4
      - run: ./pants generate-lockfiles
      - run: ./pants fmt "::"
      - run: pip install pre-commit
      - run: pre-commit run --all-files
      - run: ./pants lint "::" && ./pants typecheck "::" && ./pants test "::"
  package:
    needs: build-test
    runs-on: ubuntu-latest
    # Skip packaging in the template repository
    if: github.repository != 'MehdiZare/pantstack'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - uses: pantsbuild/actions/setup-pants@v4
      - run: ./pants generate-lockfiles
      - run: ./pants package modules/**:*image
