name: config-check
on:
  push:
    branches: [dev, main]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    # Skip this check in the template repository
    if: github.repository != 'MehdiZare/pantstack'
    steps:
      - uses: actions/checkout@v4
      - name: Verify required repo variables and secrets
        env:
          VAR_AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          VAR_AWS_REGION: ${{ vars.AWS_REGION }}
          VAR_PROJECT_SLUG: ${{ vars.PROJECT_SLUG }}
          VAR_PULUMI_ORG: ${{ vars.PULUMI_ORG }}
          SEC_PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          SEC_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SEC_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          missing=0
          for v in VAR_AWS_ACCOUNT_ID VAR_AWS_REGION VAR_PROJECT_SLUG VAR_PULUMI_ORG SEC_PULUMI_ACCESS_TOKEN SEC_AWS_ACCESS_KEY_ID SEC_AWS_SECRET_ACCESS_KEY; do
            if [ -z "${!v}" ]; then echo "Missing $v"; missing=1; fi
          done
          test $missing -eq 0
