name: semantic-pr
on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            perf
            refactor
            docs
            chore
            ci
            test
            build
          requireScope: false
          wip: true
      - name: Allow override with release labels
        if: failure()
        uses: actions-ecosystem/action-release-label@v1
        with:
          labels: release:patch,release:minor,release:major

